import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
    FileText,
    Plus,
    Search,
    Star,
    StarOff,
    MoreHorizontal,
    Clock,
    Users,
    Lock,
    Globe,
    ChevronRight,
    Sparkles,
    Share2,
    Download,
    Trash2,
    Copy
} from 'lucide-react';
import { BlockEditor, Block } from './BlockEditor';
import { Button, Input, Modal, Badge, Avatar, Card } from '../UI';

interface Document {
    id: string;
    title: string;
    icon?: string;
    cover?: string;
    starred?: boolean;
    shared?: boolean;
    updatedAt: Date;
    author: { id: string; name: string };
    blocks: Block[];
}

const MOCK_DOCS: Document[] = [
    {
        id: '1',
        title: 'Project Roadmap 2024',
        icon: '🚀',
        starred: true,
        updatedAt: new Date(Date.now() - 3600000),
        author: { id: '1', name: 'John Doe' },
        blocks: [
            { id: '1', type: 'heading1', content: 'Q1 Goals' },
            { id: '2', type: 'paragraph', content: 'Our primary focus for Q1 is to launch the unified Work OS platform.' },
            { id: '3', type: 'todo', content: 'Complete Chat module', checked: true },
            { id: '4', type: 'todo', content: 'Complete Tasks module', checked: true },
            { id: '5', type: 'todo', content: 'Complete Docs module', checked: false }
        ]
    },
    {
        id: '2',
        title: 'Meeting Notes - Team Sync',
        icon: '📝',
        updatedAt: new Date(Date.now() - 86400000),
        author: { id: '2', name: 'Sarah Smith' },
        blocks: [
            { id: '1', type: 'heading1', content: 'Team Sync - Jan 30' },
            { id: '2', type: 'heading2', content: 'Attendees' },
            { id: '3', type: 'bulletList', content: 'John, Sarah, Mike, Emily' }
        ]
    },
    {
        id: '3',
        title: 'API Documentation',
        icon: '📚',
        shared: true,
        updatedAt: new Date(Date.now() - 172800000),
        author: { id: '1', name: 'John Doe' },
        blocks: []
    }
];

export const DocsView: React.FC = () => {
    const { id } = useParams<{ id: string }>();
    const navigate = useNavigate();

    const [documents, setDocuments] = useState<Document[]>(MOCK_DOCS);
    const [activeDoc, setActiveDoc] = useState<Document | null>(
        id ? MOCK_DOCS.find(d => d.id === id) || null : null
    );
    const [searchQuery, setSearchQuery] = useState('');
    const [showAIPanel, setShowAIPanel] = useState(false);
    const [aiPrompt, setAiPrompt] = useState('');

    const filteredDocs = documents.filter(doc =>
        doc.title.toLowerCase().includes(searchQuery.toLowerCase())
    );

    const starredDocs = filteredDocs.filter(d => d.starred);
    const recentDocs = filteredDocs.filter(d => !d.starred);

    const handleCreateDoc = () => {
        const newDoc: Document = {
            id: `doc-${Date.now()}`,
            title: 'Untitled',
            icon: '📄',
            updatedAt: new Date(),
            author: { id: '1', name: 'User' },
            blocks: [{ id: '1', type: 'paragraph', content: '' }]
        };
        setDocuments([newDoc, ...documents]);
        setActiveDoc(newDoc);
        navigate(`/app/docs/${newDoc.id}`);
    };

    const handleUpdateBlocks = (blocks: Block[]) => {
        if (!activeDoc) return;
        const updatedDoc = { ...activeDoc, blocks, updatedAt: new Date() };
        setActiveDoc(updatedDoc);
        setDocuments(docs => docs.map(d => d.id === activeDoc.id ? updatedDoc : d));
    };

    const handleToggleStar = (docId: string) => {
        setDocuments(docs => docs.map(d =>
            d.id === docId ? { ...d, starred: !d.starred } : d
        ));
    };

    const handleAIWrite = async () => {
        if (!aiPrompt.trim()) return;

        // Simulate AI response
        const aiBlock: Block = {
            id: `block-${Date.now()}`,
            type: 'paragraph',
            content: `[AI Generated] Here's content about: ${aiPrompt}. This would be generated by the AI in production.`
        };

        if (activeDoc) {
            handleUpdateBlocks([...activeDoc.blocks, aiBlock]);
        }

        setAiPrompt('');
        setShowAIPanel(false);
    };

    // Document List View
    if (!activeDoc) {
        return (
            <div className="h-full flex flex-col bg-slate-950">
                {/* Header */}
                <header className="flex items-center justify-between px-6 py-4 border-b border-slate-800 bg-slate-900/50">
                    <div className="flex items-center gap-4">
                        <h1 className="text-xl font-bold text-white flex items-center gap-2">
                            <FileText className="w-6 h-6 text-indigo-400" />
                            Documents
                        </h1>
                        <div className="w-64">
                            <Input
                                placeholder="Search docs..."
                                value={searchQuery}
                                onChange={(e) => setSearchQuery(e.target.value)}
                                inputSize="sm"
                                leftIcon={<Search className="w-4 h-4" />}
                            />
                        </div>
                    </div>
                    <Button onClick={handleCreateDoc} leftIcon={<Plus className="w-4 h-4" />}>
                        New Doc
                    </Button>
                </header>

                {/* Document Grid */}
                <main className="flex-1 overflow-y-auto p-6 space-y-8">
                    {/* Starred Section */}
                    {starredDocs.length > 0 && (
                        <section>
                            <h2 className="text-sm font-medium text-slate-400 mb-4 flex items-center gap-2">
                                <Star className="w-4 h-4" />
                                Starred
                            </h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                                {starredDocs.map(doc => (
                                    <DocCard
                                        key={doc.id}
                                        doc={doc}
                                        onClick={() => {
                                            setActiveDoc(doc);
                                            navigate(`/app/docs/${doc.id}`);
                                        }}
                                        onToggleStar={() => handleToggleStar(doc.id)}
                                    />
                                ))}
                            </div>
                        </section>
                    )}

                    {/* Recent Section */}
                    <section>
                        <h2 className="text-sm font-medium text-slate-400 mb-4 flex items-center gap-2">
                            <Clock className="w-4 h-4" />
                            Recent
                        </h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
                            {recentDocs.map(doc => (
                                <DocCard
                                    key={doc.id}
                                    doc={doc}
                                    onClick={() => {
                                        setActiveDoc(doc);
                                        navigate(`/app/docs/${doc.id}`);
                                    }}
                                    onToggleStar={() => handleToggleStar(doc.id)}
                                />
                            ))}
                        </div>
                    </section>

                    {filteredDocs.length === 0 && (
                        <div className="text-center py-12">
                            <FileText className="w-12 h-12 text-slate-600 mx-auto mb-4" />
                            <h3 className="text-lg font-medium text-slate-400">No documents found</h3>
                            <p className="text-slate-500 mt-1">Create your first document to get started</p>
                            <Button onClick={handleCreateDoc} className="mt-4">
                                Create Document
                            </Button>
                        </div>
                    )}
                </main>
            </div>
        );
    }

    // Single Document Editor View
    return (
        <div className="h-full flex bg-slate-950">
            {/* Main Editor */}
            <div className="flex-1 flex flex-col">
                {/* Editor Header */}
                <header className="flex items-center justify-between px-6 py-3 border-b border-slate-800 bg-slate-900/50">
                    <div className="flex items-center gap-3">
                        <button
                            onClick={() => {
                                setActiveDoc(null);
                                navigate('/app/docs');
                            }}
                            className="text-slate-400 hover:text-white transition-colors"
                        >
                            <ChevronRight className="w-5 h-5 rotate-180" />
                        </button>

                        <span className="text-2xl">{activeDoc.icon}</span>

                        <input
                            type="text"
                            value={activeDoc.title}
                            onChange={(e) => {
                                const updated = { ...activeDoc, title: e.target.value };
                                setActiveDoc(updated);
                                setDocuments(docs => docs.map(d => d.id === activeDoc.id ? updated : d));
                            }}
                            className="text-xl font-semibold text-white bg-transparent border-none outline-none"
                            placeholder="Untitled"
                        />
                    </div>

                    <div className="flex items-center gap-2">
                        <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => setShowAIPanel(!showAIPanel)}
                            leftIcon={<Sparkles className="w-4 h-4 text-amber-400" />}
                        >
                            AI Write
                        </Button>
                        <Button variant="ghost" size="sm" leftIcon={<Share2 className="w-4 h-4" />}>
                            Share
                        </Button>
                        <button className="p-2 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white">
                            <MoreHorizontal className="w-5 h-5" />
                        </button>
                    </div>
                </header>

                {/* Editor Content */}
                <div className="flex-1 overflow-y-auto">
                    <div className="max-w-4xl mx-auto py-8 px-4">
                        <BlockEditor
                            blocks={activeDoc.blocks}
                            onChange={handleUpdateBlocks}
                        />
                    </div>
                </div>

                {/* Footer */}
                <footer className="px-6 py-2 border-t border-slate-800 bg-slate-900/50 text-xs text-slate-500 flex items-center justify-between">
                    <span>
                        Last edited {activeDoc.updatedAt.toLocaleTimeString()}
                    </span>
                    <span>
                        {activeDoc.blocks.length} blocks
                    </span>
                </footer>
            </div>

            {/* AI Panel */}
            {showAIPanel && (
                <motion.aside
                    initial={{ width: 0, opacity: 0 }}
                    animate={{ width: 320, opacity: 1 }}
                    exit={{ width: 0, opacity: 0 }}
                    className="border-l border-slate-800 bg-slate-900/50"
                >
                    <div className="w-80 p-4">
                        <div className="flex items-center justify-between mb-4">
                            <h3 className="font-semibold text-white flex items-center gap-2">
                                <Sparkles className="w-5 h-5 text-amber-400" />
                                AI Writer
                            </h3>
                            <button
                                onClick={() => setShowAIPanel(false)}
                                className="p-1 rounded hover:bg-slate-800 text-slate-400"
                            >
                                ×
                            </button>
                        </div>

                        <div className="space-y-4">
                            <textarea
                                value={aiPrompt}
                                onChange={(e) => setAiPrompt(e.target.value)}
                                placeholder="Describe what you want AI to write..."
                                className="w-full h-32 bg-slate-800 border border-slate-700 rounded-xl p-3 text-white placeholder-slate-500 resize-none"
                            />

                            <div className="space-y-2">
                                <p className="text-xs text-slate-500">Quick prompts:</p>
                                {['Summarize this document', 'Write an introduction', 'Create an outline', 'Make it more concise'].map((prompt) => (
                                    <button
                                        key={prompt}
                                        onClick={() => setAiPrompt(prompt)}
                                        className="block w-full text-left px-3 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-sm text-slate-300 transition-colors"
                                    >
                                        {prompt}
                                    </button>
                                ))}
                            </div>

                            <Button onClick={handleAIWrite} fullWidth>
                                Generate
                            </Button>
                        </div>
                    </div>
                </motion.aside>
            )}
        </div>
    );
};

// Document Card Component
const DocCard: React.FC<{
    doc: Document;
    onClick: () => void;
    onToggleStar: () => void;
}> = ({ doc, onClick, onToggleStar }) => {
    return (
        <Card hover padding="none" onClick={onClick} className="overflow-hidden">
            {/* Cover (optional) */}
            {doc.cover && (
                <div
                    className="h-24 bg-cover bg-center"
                    style={{ backgroundImage: `url(${doc.cover})` }}
                />
            )}

            <div className="p-4">
                <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                        <span className="text-2xl">{doc.icon}</span>
                        <h3 className="font-medium text-white truncate">{doc.title}</h3>
                    </div>
                    <button
                        onClick={(e) => {
                            e.stopPropagation();
                            onToggleStar();
                        }}
                        className="p-1 rounded hover:bg-slate-700 text-slate-400 hover:text-amber-400 transition-colors"
                    >
                        {doc.starred ? (
                            <Star className="w-4 h-4 fill-amber-400 text-amber-400" />
                        ) : (
                            <StarOff className="w-4 h-4" />
                        )}
                    </button>
                </div>

                <div className="flex items-center gap-3 text-xs text-slate-500">
                    <span className="flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {doc.updatedAt.toLocaleDateString()}
                    </span>
                    {doc.shared && (
                        <span className="flex items-center gap-1">
                            <Globe className="w-3 h-3" />
                            Shared
                        </span>
                    )}
                </div>
            </div>
        </Card>
    );
};

export default DocsView;
